package names

var BrazilianFirstNames = []string{
	"Benicio",
	"Cristiano",
	"Damião",
	"Danilo",
	"Edvaldo",
	"Enzo",
	"Estevão",
	"Felipe",
	"Flavio",
	"Gael",
	"Guilherme",
	"Gilberto",
	"Heitor",
	"Henrique",
	"Isaque",
	"Joaquim",
	"Luciano",
	"Mathues",
	"Nelson",
	"Octávio",
	"Orlando",
	"Pascoal",
	"Rafael",
	"Reginaldo",
	"Renato",
	"Ronaldo",
	"Salvador",
	"Sebastião",
	"Thiago",
	"Teodoro",
	"Vicente",
}

var BrazilianLastNames = map[string]float32{
	"Silva":      10.5,
	"Santos":     6.8,
	"Sousa":      4.9,
	"Oliveira":   3.1,
	"Pereira":    2.9,
	"Lima":       2.5,
	"Carvalho":   2.33,
	"Ferreira":   2.29,
	"Rodrigues":  2.27,
	"Almeida":    2.16,
	"Costa":      1.94,
	"Gomes":      1.92,
	"Martins":    1.83,
	"Araújo":     1.69,
	"Melo":       1.62,
	"Barbosa":    1.52,
	"Ribeiro":    1.503,
	"Alves":      1.48,
	"Cardoso":    1.41,
	"Schmidt":    1.33,
	"Rocha":      1.27,
	"Correa":     1.25,
	"Dias":       1.23,
	"Teixeira":   1.2,
	"Fernandes":  1.195,
	"Azevedo":    1.192,
	"Cavalcante": 1.188,
	"Montes":     1.183,
	"Gonçalves":  1.174,
}
