package names

var BrazilianFirstNames = []string{
	"Benicio",
	"Cristiano",
	"Damião",
	"Danilo",
	"Edvaldo",
	"Enzo",
	"Estevão",
	"Felipe",
	"Flavio",
	"Gael",
	"Guilherme",
	"Gilberto",
	"Heitor",
	"Henrique",
	"Isaque",
	"Joaquim",
	"Luciano",
	"Mathues",
	"Nelson",
	"Octávio",
	"Orlando",
	"Pascoal",
	"Rafael",
	"Reginaldo",
	"Renato",
	"Ronaldo",
	"Salvador",
	"Sebastião",
	"Thiago",
	"Teodoro",
	"Vicente",
}

var BrazilianLastNames = map[string]float32{
	"Silva":      11.50,
	"Santos":     8.80,
	"Sousa":      7.00,
	"Oliveira":   6.00,
	"Pereira":    3.90,
	"Lima":       3.50,
	"Carvalho":   3.33,
	"Ferreira":   3.23,
	"Rodrigues":  3.27,
	"Almeida":    3.16,
	"Costa":      2.94,
	"Gomes":      2.92,
	"Martins":    2.83,
	"Araújo":     2.69,
	"Melo":       2.62,
	"Barbosa":    2.52,
	"Ribeiro":    2.50,
	"Alves":      2.48,
	"Cardoso":    2.41,
	"Schmitz":    2.33,
	"Rocha":      2.27,
	"Correia":    2.25,
	"Dias":       2.23,
	"Teixeira":   2.20,
	"Fernandes":  2.20,
	"Azevedo":    2.19,
	"Cavalcante": 2.19,
	"Montes":     2.18,
	"Morais":     2.80,
	"Gonçalves":  2.17,
}
